<!DOCTYPE html SYSTEM "about:legacy-compat">
<html lang="en-US" data-preset="contrast" data-primary-color="#307FFF"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"><meta charset="UTF-8"><meta name="robots" content="noindex"><meta name="built-on" content="2024-11-29T17:03:54.9825047"><title>Select | Conteúdo do Curso Python para Dynamo do Revit</title><script type="application/json" id="virtual-toc-data">[{"id":"defini-o","level":0,"title":"Definição","anchor":"#defini-o"},{"id":"exemplo","level":0,"title":"Exemplo","anchor":"#exemplo"},{"id":"exerc-cio","level":0,"title":"Exercício","anchor":"#exerc-cio"}]</script><script type="application/json" id="topic-shortcuts"></script><link href="https://resources.jetbrains.com/writerside/apidoc/6.10.0-b518/app.css" rel="stylesheet"><meta name="msapplication-TileColor" content="#000000"><link rel="apple-touch-icon" sizes="180x180" href="https://jetbrains.com/apple-touch-icon.png"><link rel="icon" type="image/png" sizes="32x32" href="https://jetbrains.com/favicon-32x32.png"><link rel="icon" type="image/png" sizes="16x16" href="https://jetbrains.com/favicon-16x16.png"><meta name="msapplication-TileImage" content="https://resources.jetbrains.com/storage/ui/favicons/mstile-144x144.png"><meta name="msapplication-square70x70logo" content="https://resources.jetbrains.com/storage/ui/favicons/mstile-70x70.png"><meta name="msapplication-square150x150logo" content="https://resources.jetbrains.com/storage/ui/favicons/mstile-150x150.png"><meta name="msapplication-wide310x150logo" content="https://resources.jetbrains.com/storage/ui/favicons/mstile-310x150.png"><meta name="msapplication-square310x310logo" content="https://resources.jetbrains.com/storage/ui/favicons/mstile-310x310.png"><meta name="image" content=""><!-- Open Graph --><meta property="og:title" content="Select | Conteúdo do Curso Python para Dynamo do Revit"><meta property="og:description" content=""><meta property="og:image" content=""><meta property="og:site_name" content="Conteúdo do Curso Python para Dynamo do Revit Help"><meta property="og:type" content="website"><meta property="og:locale" content="en_US"><meta property="og:url" content="writerside-documentation/select.html"><!-- End Open Graph --><!-- Twitter Card --><meta name="twitter:card" content="summary_large_image"><meta name="twitter:site" content=""><meta name="twitter:title" content="Select | Conteúdo do Curso Python para Dynamo do Revit"><meta name="twitter:description" content=""><meta name="twitter:creator" content=""><meta name="twitter:image:src" content=""><!-- End Twitter Card --><!-- Schema.org WebPage --><script type="application/ld+json">{
    "@context": "http://schema.org",
    "@type": "WebPage",
    "@id": "writerside-documentation/select.html#webpage",
    "url": "writerside-documentation/select.html",
    "name": "Select | Conteúdo do Curso Python para Dynamo do Revit",
    "description": "",
    "image": "",
    "inLanguage":"en-US"
}</script><!-- End Schema.org --><!-- Schema.org WebSite --><script type="application/ld+json">{
    "@type": "WebSite",
    "@id": "writerside-documentation/#website",
    "url": "writerside-documentation/",
    "name": "Conteúdo do Curso Python para Dynamo do Revit Help"
}</script><!-- End Schema.org --></head><body data-id="Select" data-main-title="Select" data-article-props="{&quot;seeAlsoStyle&quot;:&quot;links&quot;}" data-template="article" data-breadcrumbs="Aula-007.md|Aula 007///Linq.md|Linq"><div class="wrapper"><main class="panel _main"><header class="panel__header"><div class="container"><h3>Conteúdo do Curso Python para Dynamo do Revit  Help</h3><div class="panel-trigger"></div></div></header><section class="panel__content"><div class="container"><article class="article" data-shortcut-switcher="inactive"><h1 data-toc="Select" id="Select.md">Select</h1><section class="chapter"><h2 id="defini-o" data-toc="defini-o">Defini&ccedil;&atilde;o</h2><p id="-xriil8_6">O m&eacute;todo <code class="code" id="-xriil8_8">Select</code> &eacute; utilizado para <span class="control" id="-xriil8_9">aplicar</span> uma fun&ccedil;&atilde;o a cada elemento da cole&ccedil;&atilde;o.</p><aside class="prompt" data-type="warning" data-title="" id="-xriil8_7"><p id="-xriil8_10">Apesar do nome <code class="code" id="-xriil8_12">Select</code> dar a entender que estamos &quot;selecionando&quot; algo, na verdade, estamos <span class="control" id="-xriil8_13">aplicando</span> uma fun&ccedil;&atilde;o a cada elemento da cole&ccedil;&atilde;o.</p><p id="-xriil8_11">Portanto, n&atilde;o confunda o m&eacute;todo <code class="code" id="-xriil8_14">Select</code> com o m&eacute;todo <code class="code" id="-xriil8_15">Where</code>.</p></aside></section><section class="chapter"><h2 id="exemplo" data-toc="exemplo">Exemplo</h2><p id="-xriil8_16">Vamos supor que tenhamos uma lista de n&uacute;meros e queremos obter o quadrado de cada um deles.</p><p id="-xriil8_17">Usando o m&eacute;todo <code class="code" id="-xriil8_25">Select</code> do <span class="control" id="-xriil8_26">Linq</span> podemos fazer isso de forma muito mais eficiente e simples, sem a necessidade de usar um la&ccedil;o <code class="code" id="-xriil8_27">for</code>.</p><div class="code-block" data-lang="python">
import clr

# Adiciona a referência para o System.Core
clr.AddReference(&quot;System.Core&quot;)

# Importa os métodos de extensão do LINQ.
import System
clr.ImportExtensions(System.Linq)

# input pela porta do node Python Script no Dynamo
numeros = IN[0]

quadrados = numeros.Select(lambda n: n ** 2)

OUT = quadrados
</div><figure id="-xriil8_19"><a href="images/linq-select-squares.png" class="lightbox"><img alt="linq-select-squares.png" src="images/linq-select-squares.png" title="linq-select-squares.png" width="700" height="626"></a></figure><p id="-xriil8_20">Perceba que o c&oacute;digo acima &eacute; muito mais simples e direto do que se tiv&eacute;ssemos que usar um la&ccedil;o <code class="code" id="-xriil8_28">for</code> para percorrer a lista de n&uacute;meros.</p><aside class="prompt" data-type="note" data-title="" id="-xriil8_21"><p id="-xriil8_29">Outra grande vantagem de <span class="control" id="-xriil8_30">Linq</span> &eacute; que podemos encadear os m&eacute;todos, facilitando ainda mais o processo de lidar com cole&ccedil;&otilde;es.</p></aside><p id="-xriil8_22">Vamos supor que no exemplo anterior, queiramos obter somente os quadrados pares. Para isso, podemos encadear o m&eacute;todo <code class="code" id="-xriil8_31">Where</code> logo ap&oacute;s o <code class="code" id="-xriil8_32">Select</code>.</p><div class="code-block" data-lang="python">
import clr

# Adiciona a referência para o System.Core
clr.AddReference(&quot;System.Core&quot;)

# Importa os métodos de extensão do LINQ.
import System
clr.ImportExtensions(System.Linq)

# input pela porta do node Python Script no Dynamo
numeros = IN[0]

quadrados = \
	numeros \
	.Select(lambda n: n ** 2) \
	.Where(lambda n: n % 2 == 0)

OUT = quadrados
</div><figure id="-xriil8_24"><a href="images/linq-select-even-squares.png" class="lightbox"><img alt="linq-select-even-squares.png" src="images/linq-select-even-squares.png" title="linq-select-even-squares.png" width="700" height="577"></a></figure></section><section class="chapter"><h2 id="exerc-cio" data-toc="exerc-cio">Exerc&iacute;cio</h2><p id="-xriil8_33">Fa&ccedil;a um c&oacute;digo que obtenha o <span class="control" id="-xriil8_36"><span class="emphasis" id="-xriil8_38">Level</span></span> de todas as paredes da fam&iacute;lia <span class="emphasis" id="-xriil8_37">Basic Wall</span> do modelo.</p><aside class="prompt" data-type="tip" data-title="" id="-xriil8_34"><p id="-xriil8_39">Utilize o m&eacute;todo <code class="code" id="-xriil8_40">Select</code> para obter o <span class="control" id="-xriil8_41"><span class="emphasis" id="-xriil8_42">Level</span></span> de cada parede.</p></aside><section class="chapter"><div class="collapse"><div class="collapse__title"><h3 id="-xriil8_35" data-toc="-xriil8_35">Solu&ccedil;&atilde;o</h3></div><div class="collapse__content"><div class="code-collapse" data-lang="python" data-is-expanded="false" data-synopsis="Códgigo sem conversão para elementos do Dynamo" data-disable-link-processing="true"># FUNCTIONS
# BEGIN&gt;&gt;&gt;&gt;&gt;

def GetElementById(document, elementId): 
    return document.GetElement(elementId)

# FUNCTIONS
# END&lt;&lt;&lt;&lt;&lt;

# MAIN CODE
# BEGIN&gt;&gt;&gt;&gt;&gt;

try:
    errorReport = None
    
    basic_walls = \
        FilteredElementCollector(doc) \
        .OfClass(Wall) \
        .Where(
            lambda wall: 
            wall.WallType.Kind == WallKind.Basic
            and not wall.IsStackedWallMember
        )
    
    walls_levels = \
        basic_walls \
        .Select(lambda wall: GetElementById(doc, wall.LevelId))
    
    result = [
        basic_walls,
        walls_levels
    ]

except Exception as e:
    # if error occurs anywhere in the process catch it
    errorReport = traceback.format_exc()

# Assign your output to the OUT variable
if errorReport is None:
    OUT = result
else:
    OUT = errorReport
# MAIN CODE
# END&lt;&lt;&lt;&lt;&lt;</div><p id="-xriil8_44">Perceba que dessa forma obteremos elementos da API do Revit. Isso impedir&aacute; que eles possam ser usados por outros nodes do Dynamo</p><figure id="-xriil8_45"><a href="images/getting-walls-levels-without-convert-to-dynamo.png" class="lightbox"><img alt="getting-walls-levels-without-convert-to-dynamo" src="images/getting-walls-levels-without-convert-to-dynamo.png" title="getting-walls-levels-without-convert-to-dynamo" width="2038" height="1208"></a></figure><br><p id="-xriil8_47">Para resolver esse problema, precisamos converter esses elementos para o contexto do Dynamo como foi mostrado no t&oacute;pico <a href="converting-objects-between-revit-and-dynamo.html" id="-xriil8_52" data-tooltip="Conversão de objetos Dynamo x Revit">Convers&atilde;o de objetos Dynamo x Revit</a></p><br><div class="code-collapse" data-lang="python" data-is-expanded="false" data-synopsis="Códgigo convertendo os elementos para o Dynamo" data-disable-link-processing="true">    result = [
        basic_walls.Select(lambda wall: wall.ToDSType(True)),
        walls_levels.Select(lambda level: level.ToDSType(True))
    ]</div><figure id="-xriil8_50"><a href="images/getting-walls-levels-with-convertion-to-dynamo.png" class="lightbox"><img alt="getting-walls-levels-with-convertion-to-dynamo.png" src="images/getting-walls-levels-with-convertion-to-dynamo.png" title="getting-walls-levels-with-convertion-to-dynamo.png" width="2026" height="1199"></a></figure><p id="-xriil8_51">Baixe o c&oacute;digo final aqui 👉 <a data-external="true" id="-xriil8_53" href="resources/getting-walls-levels-with-convertion-to-dynamo.py" target="_blank" rel="noopener noreferrer">getting-walls-levels-with-convertion-to-dynamo.py</a></p></div></div></section></section><div class="last-modified">Last modified: 29 November 2024</div><div data-feedback-placeholder="true"></div><div class="navigation-links _bottom"><a href="where.html" class="navigation-links__prev">Where</a><a href="orderby.html" class="navigation-links__next">OrderBy</a></div></article><div id="disqus_thread"></div></div></section></main></div><script src="https://resources.jetbrains.com/writerside/apidoc/6.10.0-b518/app.js"></script></body></html>