<!DOCTYPE html SYSTEM "about:legacy-compat">
<html lang="en-US" data-preset="contrast" data-primary-color="#307FFF"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"><meta charset="UTF-8"><meta name="robots" content="noindex"><meta name="built-on" content="2024-11-29T17:03:55.0005051"><title>Where | Conteúdo do Curso Python para Dynamo do Revit</title><script type="application/json" id="virtual-toc-data">[{"id":"defini-o","level":0,"title":"Definição","anchor":"#defini-o"},{"id":"exemplo","level":0,"title":"Exemplo","anchor":"#exemplo"},{"id":"exerc-cio","level":0,"title":"Exercício","anchor":"#exerc-cio"}]</script><script type="application/json" id="topic-shortcuts"></script><link href="https://resources.jetbrains.com/writerside/apidoc/6.10.0-b518/app.css" rel="stylesheet"><meta name="msapplication-TileColor" content="#000000"><link rel="apple-touch-icon" sizes="180x180" href="https://jetbrains.com/apple-touch-icon.png"><link rel="icon" type="image/png" sizes="32x32" href="https://jetbrains.com/favicon-32x32.png"><link rel="icon" type="image/png" sizes="16x16" href="https://jetbrains.com/favicon-16x16.png"><meta name="msapplication-TileImage" content="https://resources.jetbrains.com/storage/ui/favicons/mstile-144x144.png"><meta name="msapplication-square70x70logo" content="https://resources.jetbrains.com/storage/ui/favicons/mstile-70x70.png"><meta name="msapplication-square150x150logo" content="https://resources.jetbrains.com/storage/ui/favicons/mstile-150x150.png"><meta name="msapplication-wide310x150logo" content="https://resources.jetbrains.com/storage/ui/favicons/mstile-310x150.png"><meta name="msapplication-square310x310logo" content="https://resources.jetbrains.com/storage/ui/favicons/mstile-310x310.png"><meta name="image" content=""><!-- Open Graph --><meta property="og:title" content="Where | Conteúdo do Curso Python para Dynamo do Revit"><meta property="og:description" content=""><meta property="og:image" content=""><meta property="og:site_name" content="Conteúdo do Curso Python para Dynamo do Revit Help"><meta property="og:type" content="website"><meta property="og:locale" content="en_US"><meta property="og:url" content="writerside-documentation/where.html"><!-- End Open Graph --><!-- Twitter Card --><meta name="twitter:card" content="summary_large_image"><meta name="twitter:site" content=""><meta name="twitter:title" content="Where | Conteúdo do Curso Python para Dynamo do Revit"><meta name="twitter:description" content=""><meta name="twitter:creator" content=""><meta name="twitter:image:src" content=""><!-- End Twitter Card --><!-- Schema.org WebPage --><script type="application/ld+json">{
    "@context": "http://schema.org",
    "@type": "WebPage",
    "@id": "writerside-documentation/where.html#webpage",
    "url": "writerside-documentation/where.html",
    "name": "Where | Conteúdo do Curso Python para Dynamo do Revit",
    "description": "",
    "image": "",
    "inLanguage":"en-US"
}</script><!-- End Schema.org --><!-- Schema.org WebSite --><script type="application/ld+json">{
    "@type": "WebSite",
    "@id": "writerside-documentation/#website",
    "url": "writerside-documentation/",
    "name": "Conteúdo do Curso Python para Dynamo do Revit Help"
}</script><!-- End Schema.org --></head><body data-id="Where" data-main-title="Where" data-article-props="{&quot;seeAlsoStyle&quot;:&quot;links&quot;}" data-template="article" data-breadcrumbs="Aula-007.md|Aula 007///Linq.md|Linq"><div class="wrapper"><main class="panel _main"><header class="panel__header"><div class="container"><h3>Conteúdo do Curso Python para Dynamo do Revit  Help</h3><div class="panel-trigger"></div></div></header><section class="panel__content"><div class="container"><article class="article" data-shortcut-switcher="inactive"><h1 data-toc="Where" id="Where.md">Where</h1><section class="chapter"><h2 id="defini-o" data-toc="defini-o">Defini&ccedil;&atilde;o</h2><p id="-nlpvr1_6">O m&eacute;todo <code class="code" id="-nlpvr1_9">Where</code> &eacute; utilizado para <span class="control" id="-nlpvr1_10">filtrar</span> uma sequ&ecirc;ncia de valores com base em um predicado.</p><aside class="prompt" data-type="note" data-title="" id="-nlpvr1_7"><p>Um <b id="-nlpvr1_11">predicado</b> &eacute; uma fun&ccedil;&atilde;o que retorna um valor booleano, ou seja, <code class="code" id="-nlpvr1_12">True</code> ou <code class="code" id="-nlpvr1_13">False</code>.</p></aside><p id="-nlpvr1_8">Vimos no t&oacute;pico <a href="template-python-onbim.html#importa-os-m-todos-de-extens-o-do-linq" id="-nlpvr1_14" data-tooltip="Linq é uma biblioteca do .NET que permite realizar consultas em coleções de objetos.">Importa os m&eacute;todos de extens&atilde;o do Linq</a> que para usar os m&eacute;todos de extens&atilde;o do <span class="control" id="-nlpvr1_15">Linq</span> no IronPython antes precisamos import&aacute;-lo.</p></section><section class="chapter"><h2 id="exemplo" data-toc="exemplo">Exemplo</h2><div class="code-block" data-lang="python">
import clr

# Adiciona a referência para o System.Core
clr.AddReference(&quot;System.Core&quot;)

# Importa os métodos de extensão do LINQ.
import System
clr.ImportExtensions(System.Linq)

numeros = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

pares = numeros.Where(lambda n: n % 2 == 0)

OUT = pares
</div><figure id="-nlpvr1_17"><a href="images/where-even-numbers.png" class="lightbox"><img alt="where-even-numbers.png" src="images/where-even-numbers.png" title="where-even-numbers.png" width="700" height="334"></a></figure><p id="-nlpvr1_18">S&oacute; para exemplificar, veja como ficaria nosso c&oacute;digo se utiliz&aacute;ssemos uma fun&ccedil;&atilde;o convencional ao inv&eacute;s de uma <code class="code" id="-nlpvr1_24">lambda</code>.</p><div class="code-block" data-lang="python">
import clr

# Adiciona a referência para o System.Core
clr.AddReference(&quot;System.Core&quot;)

# Importa os métodos de extensão do LINQ.
import System
clr.ImportExtensions(System.Linq)

def is_even(n):
	return n % 2 == 0
	
numeros = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

pares = numeros.Where(is_even)

OUT = pares
</div><aside class="prompt" data-type="tip" data-title="" id="-nlpvr1_20"><p>Isso ser&aacute; &uacute;til quando precisarmos passar uma fun&ccedil;&atilde;o mais complexa.</p></aside><aside class="prompt" data-type="warning" data-title="" id="-nlpvr1_21"><p>Perceba que ambos os c&oacute;digos s&oacute; ser&atilde;o executados se utilizarmos o <b id="-nlpvr1_25">IronPython</b>.</p></aside><p id="-nlpvr1_22">Como mostrado na imagem abaixo, veja que se tentarmos executar esse c&oacute;digo no <span class="control" id="-nlpvr1_26">CPython</span> teremos um erro. O m&eacute;todo <code class="code" id="-nlpvr1_27">Where</code> n&atilde;o &eacute; reconhecido, uma vez que o <span class="control" id="-nlpvr1_28">CPython</span> n&atilde;o funciona com os recursos do .NET como o <span class="control" id="-nlpvr1_29">Linq</span>.</p><figure id="-nlpvr1_23"><a href="images/error-running-system-on-cpython.png" class="lightbox"><img alt="error-running-system-on-cpython.png" src="images/error-running-system-on-cpython.png" title="error-running-system-on-cpython.png" width="700" height="317"></a></figure></section><section class="chapter"><h2 id="exerc-cio" data-toc="exerc-cio">Exerc&iacute;cio</h2><p id="-nlpvr1_30">No exemplo mostrado em <a href="coleta-de-elementos.html#usando-um-elementlogicalfilter" id="-nlpvr1_33" data-tooltip="Vamos usar o ElementLogicalFilter para combinar dois filtros.">
Usando um ElementLogicalFilter
</a>, onde coletamos todas as <span class="emphasis" id="-nlpvr1_34">Furnitures</span> e <span class="emphasis" id="-nlpvr1_35">Caseworks</span> que est&atilde;o sobre um piso, adapte o c&oacute;digo utilzando o m&eacute;todo <code class="code" id="-nlpvr1_36">Where</code> para filtrar somente os elementos que s&atilde;o <span class="emphasis" id="-nlpvr1_37">Chairs</span> (cadeiras).</p><aside class="prompt" data-type="tip" data-title="" id="-nlpvr1_31"><p id="-nlpvr1_38">Utilize o Revit Lookup para inspecionar as propriedades dos elementos e escolher a que melhor resolve o problema.</p></aside><section class="chapter"><div class="collapse"><div class="collapse__title"><h3 id="-nlpvr1_32" data-toc="-nlpvr1_32">Solu&ccedil;&atilde;o</h3></div><div class="collapse__content"><div class="code-collapse" data-lang="python" data-is-expanded="false" data-synopsis="Código final" data-disable-link-processing="true"># by onBIM Technology
# www.onbim.net
# file name: ./resources/python/collecting-chairs.py

# REFERENCES AND IMPORTS
# BEGIN&gt;&gt;&gt;&gt;&gt;

import clr
import System

# &lt;&lt;&lt; Python Modules &gt;&gt;&gt;
# BEGIN

# Import traceback module from Iron Python
import traceback

# END

# Import System Libraries
clr.AddReference(&quot;System.Core&quot;)
from System.Collections.Generic import List as SystemList

# Import Linq
clr.ImportExtensions(System.Linq)

# Import Dynamo Library Nodes - Geometry
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript import Geometry as DynamoGeometry

# Import Dynamo Library Nodes - Revit
clr.AddReference(&quot;RevitNodes&quot;)
import Revit as RevitNodes

# Import ToDSType(bool) extension method
clr.ImportExtensions(RevitNodes.Elements)
clr.ImportExtensions(RevitNodes.GeometryConversion)

# Import DocumentManager and TransactionManager
clr.AddReference(&quot;RevitServices&quot;)
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

# Import Revit API
clr.AddReference(&quot;RevitAPI&quot;)
import Autodesk
from Autodesk.Revit.DB import *

# REFERENCES AND IMPORTS
# END&lt;&lt;&lt;&lt;&lt;

# INPUTS AND VARIABLES DECLARATIONS
# BEGIN&gt;&gt;&gt;&gt;&gt;

doc = DocumentManager.Instance.CurrentDBDocument

result = []

# INPUTS AND VARIABLES DECLARATIONS
# END&lt;&lt;&lt;&lt;&lt;

# MAIN CODE
# BEGIN&gt;&gt;&gt;&gt;&gt;

try:
    errorReport = None
    
    # Já que as cadeiras estão na categoria Furniture,
    # vamos criar um filtro de categoria para Furniture.
    catFilter = ElementCategoryFilter(BuiltInCategory.OST_Furniture)
    
    # Obtendo o piso a partir da seleção do usuário no Dynamo
    floor = UnwrapElement(IN[0])
    
    bbox = floor.get_BoundingBox(None)
    outline = Outline(bbox.Min, bbox.Max)
    
    # Criando um filtro de interseção de BoundingBox
    bboxIntersectsFilter = BoundingBoxIntersectsFilter(outline)
    
    # Criando um filtro lógico AND
    filtersToCombine = SystemList[ElementFilter]([
        catFilter,
        bboxIntersectsFilter
    ])
    
    logicalAndFilter = LogicalAndFilter(filtersToCombine)
    
    furnitures_and_caseworks_on_floor = \
        FilteredElementCollector(doc) \
        .WherePasses(logicalAndFilter) \
        .Where(lambda element: &quot;Chair&quot; in element.Name) \
        .ToList()
    
    result = furnitures_and_caseworks_on_floor

except Exception as e:
    # if error occurs anywhere in the process catch it
    errorReport = traceback.format_exc()

# Assign your output to the OUT variable
if errorReport is None:
    OUT = result
else:
    OUT = errorReport
# MAIN CODE
# END&lt;&lt;&lt;&lt;&lt;</div><figure id="-nlpvr1_40"><a href="images/collecting-chairs.png" class="lightbox"><img alt="collecting-chairs.png" src="images/collecting-chairs.png" title="collecting-chairs.png" width="600" height="498"></a></figure></div></div></section></section><div class="last-modified">Last modified: 29 November 2024</div><div data-feedback-placeholder="true"></div><div class="navigation-links _bottom"><a href="linq.html" class="navigation-links__prev">Linq</a><a href="select.html" class="navigation-links__next">Select</a></div></article><div id="disqus_thread"></div></div></section></main></div><script src="https://resources.jetbrains.com/writerside/apidoc/6.10.0-b518/app.js"></script></body></html>